In [1]:
!pip install requests
!pip install bs4

Requirement already satisfied: requests in c:\users\nikhi\anaconda3\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nikhi\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nikhi\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nikhi\anaconda3\lib\site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nikhi\anaconda3\lib\site-packages (from requests) (2023.7.22)
Requirement already satisfied: bs4 in c:\users\nikhi\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\nikhi\anaconda3\lib\site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\nikhi\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.4)

### Q1. --> Write a python program to display all the header tags from wikipedia.org.

In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = 'https://en.wikipedia.org/wiki/Main_Page'

In [4]:
page = requests.get(url)

In [5]:
page

In [6]:
soup = BeautifulSoup(page.text,'html.parser')

In [73]:
heading_tags =['h1','h2']

In [74]:
for tags in soup.find_all(heading_tags):
    print(tags.name + ' -> ' + tags.text.strip())

h1 -> Main Page
h1 -> Welcome to Wikipedia
h2 -> From today's featured article
h2 -> Did you know ...
h2 -> In the news
h2 -> On this day
h2 -> Today's featured picture
h2 -> Other areas of Wikipedia
h2 -> Wikipedia's sister projects
h2 -> Wikipedia languages

### Q.2)	Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [7]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [8]:
page = requests.get('https://www.imdb.com/list/ls091520106/')
page

In [9]:
soup = BeautifulSoup(page.content,'html.parser')

In [199]:
movie_name = soup.find('h3',class_="lister-item-header")

In [204]:
movie_list = []
for i in soup.find_all('h3',class_="lister-item-header"):
    movie_list.append(i.text.replace('\n',''))
movie_list

['1.The Shawshank Redemption(1994)',
 '2.The Godfather(1972)',
 '3.The Godfather Part II(1974)',
 '4.The Dark Knight(2008)',
 '5.12 Angry Men(1957)',
 "6.Schindler's List(1993)",
 '7.The Lord of the Rings: The Return of the King(2003)',
 '8.Pulp Fiction(1994)',
 '9.Il buono, il brutto, il cattivo(1966)',
 '10.Fight Club(1999)',
 '11.Joker(I) (2019)',
 '12.The Lord of the Rings: The Fellowship of the Ring(2001)',
 '13.Forrest Gump(1994)',
 '14.Inception(2010)',
 '15.Star Wars: Episode V - The Empire Strikes Back(1980)',
 '16.The Lord of the Rings: The Two Towers(2002)',
 '17.The Matrix(1999)',
 "18.One Flew Over the Cuckoo's Nest(1975)",
 '19.Goodfellas(1990)',
 '20.Shichinin no samurai(1954)',
 '21.Se7en(1995)',
 '22.Cidade de Deus(2002)',
 '23.La vita è bella(1997)',
 '24.The Silence of the Lambs(1991)',
 '25.Star Wars(1977)',
 "26.It's a Wonderful Life(1946)",
 '27.Saving Private Ryan(1998)',
 '28.Sen to Chihiro no kamikakushi(2001)',
 '29.The Green Mile(1999)',
 '30.Léon(1994)',
 '31.Seppuku(1962)',
 '32.Interstellar(2014)',
 '33.The Usual Suspects(1995)',
 '34.The Lion King(1994)',
 '35.American History X(1998)',
 '36.Back to the Future(1985)',
 '37.The Pianist(2002)',
 '38.Modern Times(1936)',
 '39.Terminator 2: Judgment Day(1991)',
 '40.The Intouchables(2011)',
 '41.Psycho(1960)',
 '42.Gladiator(2000)',
 '43.City Lights(1931)',
 '44.The Departed(2006)',
 '45.Whiplash(2014)',
 '46.Once Upon a Time in the West(1968)',
 '47.The Prestige(2006)',
 '48.Avengers: Endgame(2019)',
 '49.Casablanca(1942)',
 '50.Hotaru no haka(1988)',
 '51.Rear Window(1954)',
 '52.Nuovo Cinema Paradiso(1988)',
 '53.Alien(1979)',
 '54.Raiders of the Lost Ark(1981)',
 '55.Memento(2000)',
 '56.Apocalypse Now(1979)',
 '57.The Great Dictator(1940)',
 '58.The Lives of Others(2006)',
 '59.Avengers: Infinity War(2018)',
 '60.Django Unchained(2012)',
 '61.Spider-Man: Into the Spider-Verse(2018)',
 '62.The Shining(1980)',
 '63.Paths of Glory(1957)',
 '64.WALL·E(2008)',
 '65.Sunset Blvd.(1950)',
 '66.Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb(1964)',
 '67.Mononoke-hime(1997)',
 '68.Oldeuboi(2003)',
 '69.Witness for the Prosecution(1957)',
 '70.The Dark Knight Rises(2012)',
 '71.Once Upon a Time in America(1984)',
 '72.Gisaengchung(2019)',
 '73.Aliens(1986)',
 '74.American Beauty(1999)',
 '75.Coco(I) (2017)',
 '76.Kimi no na wa.(2016)',
 '77.Braveheart(1995)',
 '78.Das Boot(1981)',
 '79.3 Idiots(2009)',
 '80.Taare Zameen Par(2007)',
 '81.Star Wars: Episode VI - Return of the Jedi(1983)',
 '82.Toy Story(1995)',
 '83.Reservoir Dogs(1992)',
 '84.Amadeus(1984)',
 '85.Dangal(2016)',
 '86.Good Will Hunting(1997)',
 '87.Inglourious Basterds(2009)',
 '88.M - Eine Stadt sucht einen Mörder(1931)',
 '89.Requiem for a Dream(2000)',
 '90.2001: A Space Odyssey(1968)',
 '91.Vertigo(1958)',
 '92.Eternal Sunshine of the Spotless Mind(2004)',
 '93.Citizen Kane(1941)',
 '94.Full Metal Jacket(1987)',
 '95.Jagten(2012)',
 '96.North by Northwest(1959)',
 '97.A Clockwork Orange(1971)',
 '98.Snatch(2000)',
 "99.Le fabuleux destin d'Amélie Poulain(2001)",
 '100.The Kid(1921)']

In [203]:
year = []
for i in soup.find_all('span',class_="lister-item-year text-muted unbold"):
    year.append(i.text)
year

['(1994)',
 '(1972)',
 '(1974)',
 '(2008)',
 '(1957)',
 '(1993)',
 '(2003)',
 '(1994)',
 '(1966)',
 '(1999)',
 '(I) (2019)',
 '(2001)',
 '(1994)',
 '(2010)',
 '(1980)',
 '(2002)',
 '(1999)',
 '(1975)',
 '(1990)',
 '(1954)',
 '(1995)',
 '(2002)',
 '(1997)',
 '(1991)',
 '(1977)',
 '(1946)',
 '(1998)',
 '(2001)',
 '(1999)',
 '(1994)',
 '(1962)',
 '(2014)',
 '(1995)',
 '(1994)',
 '(1998)',
 '(1985)',
 '(2002)',
 '(1936)',
 '(1991)',
 '(2011)',
 '(1960)',
 '(2000)',
 '(1931)',
 '(2006)',
 '(2014)',
 '(1968)',
 '(2006)',
 '(2019)',
 '(1942)',
 '(1988)',
 '(1954)',
 '(1988)',
 '(1979)',
 '(1981)',
 '(2000)',
 '(1979)',
 '(1940)',
 '(2006)',
 '(2018)',
 '(2012)',
 '(2018)',
 '(1980)',
 '(1957)',
 '(2008)',
 '(1950)',
 '(1964)',
 '(1997)',
 '(2003)',
 '(1957)',
 '(2012)',
 '(1984)',
 '(2019)',
 '(1986)',
 '(1999)',
 '(I) (2017)',
 '(2016)',
 '(1995)',
 '(1981)',
 '(2009)',
 '(2007)',
 '(1983)',
 '(1995)',
 '(1992)',
 '(1984)',
 '(2016)',
 '(1997)',
 '(2009)',
 '(1931)',
 '(2000)',
 '(1968)',
 '(1958)',
 '(2004)',
 '(1941)',
 '(1987)',
 '(2012)',
 '(1959)',
 '(1971)',
 '(2000)',
 '(2001)',
 '(1921)']

In [206]:
Rating = []
for i in soup.find_all('span',class_="ipl-rating-star__rating"):
    Rating.append(i.text)
    
Rating

['9.3',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.4',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.7',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.7',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.7',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.7',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.7',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 ...]

### Q.3)	Write a python program to scrape mentioned details from dineout.co.in : i) Restaurant name ii) Cuisine iii) Location iv) Ratings v) Image URL.

In [139]:
from bs4 import BeautifulSoup
import requests

In [140]:
page = requests.get('https://www.dineout.co.in/delhi-restaurants/welcome-back')

In [141]:
page

In [142]:
soup = BeautifulSoup(page.content)

### extract Name

In [144]:
restra_name = soup.find('div',class_="restnt-info cursor")

In [145]:
restra_name.text

'The G.T. RoadM-Block,Connaught Place, Central Delhi'

### Extract location

In [146]:
location = soup.find('div',class_="restnt-loc ellipsis")

In [147]:
location.text

'M-Block,Connaught Place, Central Delhi'

### Extract rating

In [148]:
rating = soup.find('div',class_="restnt-rating rating-4")

In [149]:
rating.text

'4.3'

### Image URL

In [151]:
images = []
for i in soup.find_all('img',class_="no-img"):
    images.append(i['data-src'])
images

['https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/m/u/p31393-15972091555f337a43bb961.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/d/f/p19636-16463919576221f295ae1f1.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/t/u/p237-16468990666229af7a72b08.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/e/u/p80493-16064603115fc0a397716de.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/e/y/p20941-168915645564ae7b673b872.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/z/c/p19259-1686039280647eeaf0c8440.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/a/j/p20996-145631488756cd9a0796608.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/n/c/p3007-15706949095d9ee6fd0b8b4.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/o/b/p1317-15164263275a62d457c112d.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/y/y/p4199-164188203361dd21b1a3174.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/s/d/p21171-1704789340659d055c4e182.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/j/a/p54792-1630486205612f3ebd9d20b.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/f/s/p2669-1499666296596317787f36d.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/y/m/p221-16455303976214cd1d7a086.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/e/u/p456-14473237645644687422a28.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/t/h/p16-16457922496218cbf9e6961.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/k/k/p77626-1700647577655dd299664b4.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/k/v/p3094-1617661641606b8ec9027d2.JPG?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/a/y/p73298-15790901205e1f00c8aa465.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/s/y/p20298-1664186585633178d99f1db.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/s/j/p19748-170565875165aa497ff347d.jpg?tr=tr:n-medium']

### Cuisine

In [152]:
cuisines = soup.find_all('span', class_='double-line-ellipsis')

In [153]:
cuisine_list = []

In [154]:
for cuisine in cuisines:
    cuisine_list.append(cuisine.text.strip())

In [155]:
cuisine_list

['₹ 2,000 for 2 (approx) | North Indian',
 '₹ 1,500 for 2 (approx) | North Indian, Chinese',
 '₹ 1,300 for 2 (approx) | Chinese, Thai',
 '₹ 1,400 for 2 (approx) | North Indian, Continental',
 '₹ 2,500 for 2 (approx) | North Indian, Italian, Chinese, Turkish, Continental',
 '₹ 1,200 for 2 (approx) | North Indian',
 '₹ 2,000 for 2 (approx) | Continental, Asian, Italian, North Indian',
 '₹ 1,500 for 2 (approx) | Tibetan, Nepalese',
 '₹ 2,000 for 2 (approx) | Italian, Beverages',
 '₹ 2,000 for 2 (approx) | Modern Indian, Continental, Finger Food',
 '₹ 2,700 for 2 (approx) | North Indian, Chinese, Continental',
 '₹ 2,200 for 2 (approx) | North Indian, Mughlai',
 '₹ 2,200 for 2 (approx) | Chinese, Thai, Continental, North Indian, Asian',
 '₹ 2,000 for 2 (approx) | North Indian, Chinese, Italian, Continental',
 '₹ 2,400 for 2 (approx) | North Indian, European, Fast Food, Italian, Continental',
 '₹ 500 for 2 (approx) | Fast Food',
 '₹ 1,800 for 2 (approx) | North Indian, Continental, Asian, Chinese',
 '₹ 2,600 for 2 (approx) | Mughlai, North Indian',
 '₹ 2,600 for 2 (approx) | North Indian, Italian, Asian, Mughlai, Desserts',
 '₹ 2,100 for 2 (approx) | North Indian, Continental, Chinese, Fast Food',
 '₹ 2,000 for 2 (approx) | North Indian, Asian, Italian']

### Q. 4)	Write s python program to display list of respected former finance minister of India(i.e. Name , Term of office) from https://presidentofindia.nic.in/former-presidents.htm and make data frame.

In [10]:
url = requests.get('https://presidentofindia.nic.in/former-presidents')

In [11]:
soup = BeautifulSoup(url.text)

In [183]:
name= []
for i in soup.find_all('div',class_= "desc-sec"):
    name.append(i.text.replace('\n',' '))

In [184]:
name

[' Shri Ram Nath Kovind 14th President of India ',
 ' Shri Pranab Mukherjee 13th President of India ',
 ' Smt Pratibha Devisingh Patil 12th President of India ',
 ' DR. A.P.J. Abdul Kalam 11th President of India ',
 ' Shri K. R. Narayanan 10th President of India ',
 ' Dr Shankar Dayal Sharma 9th  President of India ',
 ' Shri R Venkataraman 8th President of India ',
 ' Giani Zail Singh 7th President of India ',
 ' Shri Neelam Sanjiva Reddy 6th President of India ',
 ' Dr. Fakhruddin Ali Ahmed 5th President of India ',
 ' Shri Varahagiri Venkata Giri 4th President of India ',
 ' Dr. Zakir Husain 3rd President of India ',
 ' Dr. Sarvepalli Radhakrishnan 2nd President of India ',
 ' Dr. Rajendra Prasad 1st President of India ']